#! /bin/bash

vpp_ws_dir=$1

if [ -z "${vpp_ws_dir}" ]; then
    echo "Usage: $0 <vpp-ws-dir>" >&2
    exit 1
fi

cargo build || exit $?

if [ ! -d venv ]; then
    python3 -mvenv venv || exit $?

    source venv/bin/activate

    pip install --upgrade pip || exit $?
    pip install -r tests/requirements.txt || exit $?
else
    source venv/bin/activate
fi

cd tests

mkdir -p plugin-libs || exit $?

ln -f ../target/debug/libvpp_example_plugin.so plugin-libs/example_plugin.so || exit $?
ln -f ../target/debug/libvpp_test_plugin.so plugin-libs/test_plugin.so || exit $?
ln -f ../target/debug/libvpp_test_version_mismatch_plugin.so plugin-libs/version_mismatch_plugin.so || exit $?

python3 run_tests.py --vpp-tag=vpp --vpp-ws-dir="${vpp_ws_dir}" --filter *.*.* --extern-plugin-dir $(pwd)/plugin-libs/
rc=$?

if [ -n "$OUTPUT_LOGS_ON_FAILURE" ]; then
    shopt -s nullglob
    for failed_log_file in /tmp/vpp-unittest-*-FAILED/log.txt; do
        echo "$failed_log_file:"
        cat "$failed_log_file"
    done
fi

exit $rc
