name: Continuous Integration

on: [push, pull_request]

env:
  rust_stable: stable
  rust_clippy: '1.93.0'
  rust_nightly: nightly-2026-04-24
  vpp: '26.02'
  CCACHE_DIR: ${{ github.workspace }}/.ccache

jobs:
  formatting:
    name: Check formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Check formatting
        run: cargo fmt --all -- --check

  clippy:
    name: Check clippy lints
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install Rust ${{ env.rust_clippy }}
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.rust_clippy }}
          components: clippy
      - uses: Swatinem/rust-cache@v2
      - name: "cargo clippy --workspace --all-targets --all-features --no-deps -- -D warnings"
        run: cargo clippy --workspace --all-targets --all-features --no-deps -- -D warnings

  docs:
    name: Check documentation builds
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install Rust ${{ env.rust_stable }}
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.rust_stable }}
      - uses: Swatinem/rust-cache@v2
      - name: "cargo doc --no-deps"
        run: cargo doc --no-deps
        env:
          # To catch warnings as well as errors by turning them into a job failure
          RUSTDOCFLAGS: -Dwarnings

  tests:
    name: Run tests (${{ matrix.runner }})
    runs-on: ${{ matrix.runner }}
    strategy:
      # It's useful to know all of the failures up front in case they are different between the
      # variants
      fail-fast: false
      matrix:
        runner: ['ubuntu-24.04', 'ubuntu-24.04-arm']
    steps:
      - uses: actions/checkout@v5
      - name: Install Rust ${{ env.rust_stable }}
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.rust_stable }}
      - uses: Swatinem/rust-cache@v2
      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: vpp-${{ env.vpp }}-${{ matrix.runner }}
      - name: Install vpp ${{ env.vpp }}
        run: |
          export PATH="/usr/lib/ccache:/usr/local/opt/ccache/libexec:$PATH"
          srcdir="$(pwd)"
          mkdir /tmp/build
          cd /tmp/build
          git clone --depth 1 -b v${{ env.vpp }} https://gerrit.fd.io/r/vpp
          cd vpp
          make install-dep
          make pkg-deb
          sudo dpkg -i build-root/*.deb
      - name: Run unit tests
        run: cargo test --workspace
      - name: Run integration tests
        run: tests/run /tmp/build/vpp
        env:
          OUTPUT_LOGS_ON_FAILURE: 1

  tests-nightly:
    name: Run tests with nightly Rust (${{ matrix.runner }})
    runs-on: ${{ matrix.runner }}
    strategy:
      # It's useful to know all of the failures up front in case they are different between the
      # variants
      fail-fast: false
      matrix:
        runner: ['ubuntu-24.04']
    steps:
      - uses: actions/checkout@v5
      - name: Install Rust ${{ env.rust_nightly }}
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.rust_nightly }}
          components: rust-src
      - uses: Swatinem/rust-cache@v2
      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: vpp-asan-${{ env.vpp }}-${{ matrix.runner }}
      - name: Install vpp ${{ env.vpp }}
        run: |
          export PATH="/usr/lib/ccache:/usr/local/opt/ccache/libexec:$PATH"
          srcdir="$(pwd)"
          mkdir /tmp/build
          cd /tmp/build
          git clone --depth 1 -b v${{ env.vpp }} https://gerrit.fd.io/r/vpp
          cd vpp
          make install-dep
          make pkg-deb VPP_EXTRA_CMAKE_ARGS=-DVPP_ENABLE_SANITIZE_ADDR=ON
          sudo dpkg -i build-root/*.deb
      - name: Build build scripts and proc-macros
        run: cargo check --workspace
      - name: Run unit tests with ASAN
        run: cargo test --workspace
        env:
          RUSTFLAGS: -Z sanitizer=address
          ASAN_OPTIONS: poison_history_size=128
      - name: Run integration tests
        run: tests/run --asan /tmp/build/vpp
        env:
          OUTPUT_LOGS_ON_FAILURE: 1
          ASAN_OPTIONS: poison_history_size=128
